### ISSUE TITLE
Questions about producer behaviors

### ISSUE THREAD

**Issue by ABNER-1** [streamnative/pulsar-tracing#11]
Thans for this good job.

When studying the code about this project, I have been confused by the producer interceptor behavior which injects unfinished span to tracer. 
Meanwhile, I have noticed the jaeger ui result that the span indeed finished. How it worked?

Will this be finished by other function in the feature milestones? 
Will this opetation cause memory leak? 

Thank you very much.

**Comment by codelipenghui** [comment]
@ABNER-1 Could you please provide an example, I'm not sure where the problem is. Do you mean `finished is the trace finished or span finished`?

**Comment by ABNER-1** [comment]
Sorry, `fininshed` in `Will this be finished by other function in the feature milestones?`  means span finished.

Source code is this.
```java
   @Override
    public Message<?> beforeSend(Producer producer, Message message) {
        Tracer tracer = GlobalTracer.get();
        TracingPulsarUtils.buildAndInjectSpan(message, producer, tracer).finish();
        return message;
    }
```
I only find operators of span in producerInterceptor.

 I am just confused by that span is unfinished in this code,

Thank you for replying.

**Comment by ABNER-1** [comment]
So, the distinguish of producerInceptor and consumerInceptor is 
1. producer inject and finsh
2. consumer finsh and inject
